#define ASCII_BACKSLASH 92
#define ASCII_COMMA 44
#define ASCII_CARRIAGE_RETURN 13
#define ASCII_DOLLAR 36
#define ASCII_LINE_END 10
//#define ASCII_FSLASH 47
#define ASCII_HASH 35
#define ASCII_SEMICOLON 59
#define ASCII_FULLSTOP 46
#define ASCII_SPACE 32
#define ASCII_SPEECHMARK 34

#define ASCII_B 66
//#define ASCII_G 71
#define ASCII_M 77
//#define ASCII_LOWA 97
//#define ASCII_LOWF 102


#define ATASCII_SIZE 1024 // ATASCII is 128 symbols, each made up of 8 bytes.

#define FONT_ROW 4
#define FONT_SIZE 8
#define FONT_SPACING 24
#define BIGGEST_INCREASE 28
#define MAX_FONT_ENTRIES 768
#define COMPARE_TOTAL_FILESIZE 1087
#define COMPARE_IMAGE_SIZE 995

#define COMPARE_HEADER01 66
#define COMPARE_HEADER02 77
#define COMPARE_FILESIZE_LOW 62
#define COMPARE_FILESIZE_HIGH 4
#define COMPARE_OFFSET 62
#define COMPARE_WIDTH 32
#define COMPARE_PLANE 1
#define COMPARE_DEPTH 1
#define COMPARE_COMPRES01 0
#define COMPARE_COMPRES02 0
#define COMPARE_COMPRES03 0
#define COMPARE_COMPRES04 0
